# Generated by Django 4.0.4 on 2022-05-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('upload_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='上传时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('type', models.IntegerField(choices=[(0, '图片'), (1, '视频')], default=0, verbose_name='类型')),
                ('object', models.CharField(max_length=191, unique=True, verbose_name='object')),
                ('thumbnail_status', models.BooleanField(default=False, verbose_name='压缩状态')),
                ('description', models.CharField(blank=True, max_length=191, null=True, verbose_name='照片描述')),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='机器描述')),
                ('lifecycle', models.IntegerField(choices=[(-2, '已删除'), (-1, '回收站'), (0, '待上传'), (1, '可用')], default=0, verbose_name='状态')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_user_upload_user', to='user.user', verbose_name='上传用户')),
                ('viewers', models.ManyToManyField(related_name='photo_user_viewers', to='user.user', verbose_name='查看者')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoShare',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('share_type', models.IntegerField(choices=[(0, '不限制查看'), (1, '每个人可查看一次'), (2, '仅好友可查看'), (3, '仅好友可查看一次')], default=0, verbose_name='状态')),
                ('password', models.CharField(blank=True, max_length=191, null=True, verbose_name='分享密码')),
                ('token', models.CharField(max_length=191, unique=True, verbose_name='分享Token')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo', verbose_name='照片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
                ('viewers', models.ManyToManyField(related_name='photo_share_user_viewers', to='user.user', verbose_name='查看者')),
            ],
            options={
                'verbose_name': '照片分享',
                'verbose_name_plural': '照片分享',
                'ordering': ['id'],
            },
        ),
    ]
