# Generated by Django 4.0.4 on 2022-05-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('register_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='注册时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(blank=True, max_length=191, null=True, verbose_name='用户名')),
                ('openid', models.CharField(max_length=191, unique=True, verbose_name='微信openid')),
                ('avatar', models.CharField(blank=True, max_length=1191, null=True, verbose_name='头像')),
                ('place', models.CharField(blank=True, max_length=191, null=True, verbose_name='地区')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (0, '女'), (-1, '未知')], default=-1, null=True, verbose_name='性别')),
                ('status', models.IntegerField(choices=[(1, '可用'), (0, '封禁')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('type', models.IntegerField(choices=[(1, '好友'), (-1, '拉黑')], default=-1, verbose_name='关系类型')),
                ('relationship', models.CharField(max_length=191, unique=True, verbose_name='关系Token')),
                ('twoway', models.BooleanField(default=False, verbose_name='双向好友')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userrelationship_origin', to='user.user', verbose_name='发起用户')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userrelationship_target', to='user.user', verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '用户关系',
                'verbose_name_plural': '用户关系',
                'ordering': ['id'],
            },
        ),
    ]
