# Generated by Django 4.0.4 on 2022-05-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('common', '0001_initial'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=191, verbose_name='相册名')),
                ('user_cache', models.TextField(blank=True, null=True, verbose_name='创建者缓存')),
                ('description', models.CharField(blank=True, max_length=191, null=True, verbose_name='相册描述')),
                ('record_time', models.DateTimeField(blank=True, null=True, verbose_name='记录时间')),
                ('place', models.CharField(blank=True, max_length=191, null=True, verbose_name='记录地点')),
                ('password', models.CharField(blank=True, max_length=191, null=True, verbose_name='相册密码')),
                ('acl', models.IntegerField(choices=[(0, '私密'), (1, '共享给好友'), (2, '共享给所有人'), (3, '共享给指定人')], default=0, verbose_name='权限')),
                ('photo_count', models.IntegerField(default=0, verbose_name='照片数量')),
                ('tags_cache', models.TextField(blank=True, null=True, verbose_name='标签缓存')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_photo_cover', to='photo.photo', verbose_name='封面')),
                ('pictures', models.ManyToManyField(to='photo.photo', verbose_name='图片')),
                ('tags', models.ManyToManyField(to='common.tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者')),
                ('viewers', models.ManyToManyField(related_name='album_user_viewers', to='user.user', verbose_name='查看者')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('acl_type', models.IntegerField(choices=[(-1, '所有者'), (0, '查看'), (1, '管理'), (2, '屏蔽')], default=-1, verbose_name='权限')),
                ('useralbum', models.CharField(max_length=191, unique=True, verbose_name='关系Token')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album', verbose_name='相册')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户相册关系',
                'verbose_name_plural': '用户相册关系',
                'ordering': ['id'],
            },
        ),
    ]
