# Generated by Django 4.0.4 on 2022-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='相册描述'),
        ),
    ]
